# Generated by Django 4.0.2 on 2023-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_articlecountviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecountviews',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
